Sprint 3
kt-kk8kk/middle.messenger.praktikum.yandex pull request #5
Opened 2024-12-23 20:30 UTC by kt-kk8kk

2024-12-25 20:10 UTC, aromanovnik requested changes
Добрый день, Екатерина!

Работа выполнена очень хорошо: добавлен роутинг, который работает корректно, внедрено HTTP API для чатов, авторизации и пользователей, подключен WebSocket для работы с real-time сообщениями, активно используются enum, код хорошо типизирован. Код чистый, структурированный и читаемый. Отличная работа!

Тем не менее, есть несколько замечаний, которые потребуют доработки. Более подробно о них написано в комментариях к коду.

**Что нужно исправить**:
* На Netlify опубликована неактуальная версия проекта. Перед отправкой работы на проверку необходимо убедиться, что проект обновлен и соответствует последним изменениям в репозитории.
* Если пользователь уже авторизован, необходимо настроить редирект со страниц `/` и `/sign-up` на `/messenger`, чтобы исключить возможность повторного доступа к страницам регистрации и входа.

**Что можно улучшить**:
* Современные IDE, такие как Visual Studio Code или WebStorm, имеют встроенные или подключаемые языковые модели, которые позволяют обнаруживать опечатки в названиях переменных и других идентификаторах. Это помогает избежать ошибок. 
* Постарайтесь избавиться от использования типов `any` в коде. Это делает код менее безопасным, так как `any` отключает проверку типов, что может привести к скрытым ошибкам. Если тип заранее не известен, что бывает редко, используйте `unknown`, так как он заставляет явно проверять тип перед использованием. Однако предпочтительнее сразу указывать конкретные типы, чтобы улучшить читаемость и надежность кода.
* В TypeScript не рекомендуется называть интерфейсы и классы одинаковыми именами, чтобы избежать путаницы, особенно при импортах и чтении кода. Например, можно использовать префикс `I` для интерфейсов или сделать названия более специфичными.  Пример: `class AuthPage extends Block<AuthPageProps> implements IAuthPage {}`
* После отправки сообщения лучше очищать содержимое инпута. Это улучшает пользовательский опыт, так как позволяет сразу вводить новое сообщение, не требуя от пользователя ручной очистки поля.
* При удалении или добавлении пользователя из чата было бы удобнее показывать список участников, чтобы сразу выбрать нужного, вместо того чтобы вспоминать его логин или id.
* В инпутах формы редактирования пользователя стоит отображать текущие данные, чтобы пользователю не нужно было заполнять все поля заново при изменении, например, только имени. Это повысит удобство использования и сократит время на редактирование.
* Тип `Event` является слишком общим и не предоставляет подробной информации о специфике события, что может затруднить использование свойств, характерных для конкретного события. Лучше использовать более конкретный тип, например, `MouseEvent` для событий, связанных с действиями мыши. 
* Закомментированный код лучше не оставлять в проекте, так как вся история изменений сохраняется в Git. В любой момент можно вернуться к предыдущим версиям и посмотреть старый код. Оставление закомментированных участков засоряет кодовую базу и снижает её читаемость.
* Если компонент становится слишком большим, лучше разделить его на более мелкие компоненты. Это упростит поддержку и повысит переиспользуемость отдельных частей.

Напоминаю, что работа может быть принята только после исправления всех критических замечаний **Надо исправить**.

Удачного рефакторинга кода.

2024-12-25 20:10 UTC, aromanovnik commented on src/pages/chat-list/chat-list.ts
>  class ChatListPage extends Block {
**Можно лучше**: Если компонент становится слишком большим, лучше разделить его на более мелкие компоненты. Это упростит поддержку и повысит переиспользуемость отдельных частей.

2024-12-27 21:13 UTC, kt-kk8kk commented on README.md
> +
Исправлено

2024-12-27 21:14 UTC, kt-kk8kk commented on src/pages/auth/auth.ts
>  class AuthPage extends Block {
Исправлено

2024-12-27 21:14 UTC, kt-kk8kk commented on src/pages/profile/profile.ts
> +
Пока не получается это реализовать. Постараюсь сделать эти правки при сдаче 4 спринта.

2024-12-28 08:20 UTC, aromanovnik approved these changes
Поздравляю! Ваша работа принята. Все недочеты исправлены. Желаю успехов в дальнейшей учебе!

2025-01-13 13:48 UTC, merged